### ISSUE TITLE
Getting error "No code found."

### ISSUE THREAD

**Issue by shaimona** [Widen/cloudfront-auth#11]
Followed the instructions in the Readme file. However I am getting error "No code found." in the browser. Lambda logs shows 
"Callback from OIDC provider received"
"Requesting access token."

After that lambda finish running. No other logs in the Cloudwatch log. 

Any help would be really appreciated.

**Comment by payton** [comment]
This error is a result of the callback from your auth provider not including the code within the querystring (when making the call to /_callback).

Which auth provider are you going through?
My first suggestion would be to verify that all of the values within your initial redirect are correct. Open up the config file that was generated by running the build script. Check to make sure all variables in the AUTH_REQUEST object are valid along with your discovery document URL.

I created this tool to help with debugging issues like this. It completely outputs the requests/responses into log files:
https://github.com/Widen/cloudfront-auth/wiki/Debug-&-Test

Let me know if you decide to try the debugger and need any help.

**Comment by shaimona** [comment]
I was able to fix it. It was callback

**Comment by payton** [comment]
Glad to hear it!
