### ISSUE TITLE
"Missing credentials in config" using test

### ISSUE THREAD

**Issue by theklr** [Widen/cloudfront-auth#12]
Attempting to use the Okta configuration and it's not working when I've deployed it. So I'm trying testing using the wiki however, I seem to get this response:
`{ CredentialsError: Missing credentials in config
    at ClientRequest.<anonymous> (../tests/node_modules/aws-sdk/lib/http/node.js:83:34)
    at ClientRequest.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at Socket.emitTimeout (_http_client.js:629:10)
    at Socket.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:338:8)
    at ontimeout (timers.js:386:14)
  message: 'Missing credentials in config',
  code: 'CredentialsError',
  time: 2018-06-19T20:07:50.161Z,
  retryable: true,
  originalError:
   { message: 'Could not load credentials from any providers',
     code: 'CredentialsError',
     time: 2018-06-19T20:07:50.161Z,
     retryable: true,
     originalError:
      { message: 'Connection timed out after 1000ms',
        code: 'TimeoutError',
        time: 2018-06-19T20:07:50.160Z,
        retryable: true } } } 'CredentialsError: Missing credentials in config\n    at ClientRequest.<anonymous> (../tests/node_modules/aws-sdk/lib/http/node.js:83:34)\n    at ClientRequest.g (events.js:292:16)\n    at emitNone (events.js:86:13)\n    at ClientRequest.emit (events.js:185:7)\n    at Socket.emitTimeout (_http_client.js:629:10)\n    at Socket.g (events.js:292:16)\n    at emitNone (events.js:86:13)\n    at Socket.emit (events.js:185:7)\n    at Socket._onTimeout (net.js:338:8)\n    at ontimeout (timers.js:386:14)'`
I've been trying to debug what the config parameter it's failing on but cannot seem to find it.

**Comment by payton** [comment]
Just to clarify, have you been verifying your `test-config.json` file or config file?

This error is coming directly from the AWS SDK. If you haven't already, make sure your AWS credentials in the `test-config.json` file are correct. These are updated on lines 36-41 of `tests.js`.

The test config is loading properly otherwise the test would have exited, so I would think it is something with one of the test config values.

**Comment by theklr** [comment]
This came from the test config, I’m getting an access denied when deployed

**Comment by payton** [comment]
Hm... I can try running through the testing process again tomorrow. I don't have any other suggestions at the moment as it seems to be an AWS issue. If you are having a specific issue with deployment (outside of the testing environment), feel free to make another issue.

I'll post another update, but I don't recall having an issue like that before (admittedly, it has been a while).

**Comment by theklr** [comment]
No worries, it was an AWS configuration out my hands. Thanks!
