### ISSUE TITLE
SSL errors with OpenSSH ssh-keygen

### ISSUE THREAD

**Issue by rudism** [Widen/cloudfront-auth#14]
I'm running arch linux with the following openssh and opnssl versions:

```
$ ssh -V
OpenSSH_7.9p1, OpenSSL 1.1.1  11 Sep 2018
```

The `ssh-keygen` command used to generate the private key is generating it in a new openssh key format which can't be read by openssl, for example:

```
$ ssh-keygen -t rsa -b 4096 -f test_id_rsa -N ''
Generating public/private rsa key pair.
Your identification has been saved in test_id_rsa.
Your public key has been saved in test_id_rsa.pub.
The key fingerprint is:
SHA256:OzVjTwL4zwQoDoe/daSj4S4KUA9p8QE+2m8kRQredDc rudism@rudism-archbook
The key's randomart image is: (snipped)

$ openssl rsa -in test_id_rsa -pubout -outform PEM -out id_rsa.pub
unable to load Private Key
140265992393216:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: ANY PRIVATE KEY
```

At first I didn't notice the error output during the `build.sh` process, and the result after uploading the lambda and configuring cloudfront was the following error when trying to visit the cloudfront website:

```
lambda error:0906D06C:PEM routines:PEM_read_bio:no start line
```

I was able to get it working by adding `-m PEM` to the `ssh-keygen` arguments in `build.js`, which fixes the output format to one that openssl was able to read.

**Comment by payton** [comment]
Thank you for finding this. If you would like to create a PR, I would be more than happy to merge it. Otherwise I'll make the change and be sure to credit you in the commit.
