### ISSUE TITLE
Question - Auth0 Base URL

### ISSUE THREAD

**Issue by 0xtf** [Widen/cloudfront-auth#17]
Hi there,

First of all, thanks for putting this out! 

I was following the instructions for Auth0 and I'm not entirely sure what is expected in the Base URL. Does it refer to the Auth0 "Domain Name" or the Base URL of the distribution?

Thanks!

**Comment by payton** [comment]
That's correct! It refers to the "Domain" field from Auth0.

**Comment by payton** [comment]
Added clarification to README.md
