### ISSUE TITLE
Internal Server Error - Auth0

### ISSUE THREAD

**Issue by 0xtf** [Widen/cloudfront-auth#18]
Hi,

Apologizes for another issue, which might be a personal problem and not related to the project, but I keep getting Internal Server Error with the Auth0 configuration.

The generated configuration is something along the lines of:

```
{
    "AUTH_REQUEST": {
        ...
        "response_type": "code",
        "scope": "openid email",
        "redirect_uri": "randomCF_ID.cloudfront.net/_callback"
    },
    "TOKEN_REQUEST": {
        ...
        "redirect_uri": "https://randomCF_ID.cloudfront.net/_callback",
        "grant_type": "authorization_code"
    },
    "DISTRIBUTION": "randomCF_ID.cloudfront.net",
    "AUTHN": "AUTH0",
   ...
    "DISCOVERY_DOCUMENT": "my_domain.eu.auth0.com/.well-known/openid-configuration",
    "SESSION_DURATION": 28800,
    "BASE_URL": "my_domain.eu.auth0.com",
    "CALLBACK_PATH": "/_callback",
    "AUTHZ": "AUTH0"
}
```

However, it fails with:

`2019-01-01T16:17:40.120Z	c23e78dd-0de0-11e9-996d-47ffa10428ea	Internal server error: connect ECONNREFUSED 127.0.0.1:80
`

Any thoughts?

Thank you very much!

**Comment by payton** [comment]
Ah, yes. I had this issue earlier. 

Make sure you add the protocol to your domain. It should be:
`https://my_domain.eu.auth0.com`

I'll be sure to make that more clear in the instructions, too. If you have any other issues, let us know!
