### ISSUE TITLE
Support for multiple providers (instead of choosing at build time)

### ISSUE THREAD

**Issue by rprieto** [Widen/cloudfront-auth#2]
Thanks for putting this project together, I was about to build something very similar!

What are your thoughts on supporting multiple auth providers? When the JWT is missing or expired, instead of re-directing to the provider directly, the Lambda function could render a webpage similar to what Auth0 does:

![image](https://user-images.githubusercontent.com/189105/36940805-52e767cc-1f97-11e8-84c0-31b08bf678fb.png)

**Comment by uriahcarpenter** [comment]
Hi @rprieto, at this time the project is focused on providing authorization to private content, typically, scoped to a single organization where a single authentication provider is desired.

Having multiple authentication providers would make the authorization part more difficult. Thank you for your interest!
