### ISSUE TITLE
need more details for implementing this project

### ISSUE THREAD

**Issue by sahityab** [Widen/cloudfront-auth#21]
Hello!

i am trying to implement this project on my Aws static hosted website on S3 with a cloudfront distribution infront of it. I want to secure it with OKTA. I am fumbling on some steps while following the write up you have on the read.me. Like..I selected "Web" in Okta while creating the app, and when Saml did not work, I am retrying with openId. So I am happy to see the credentials like the client id and client secret while using openid but I am not knowing exactly what to give for base url and redirect uri when I am prompted to on the command prompt. Also, after entering everything, (I entered the CF domain url for base url and redirect url-added index.html to it, considering it as the call back ), it ran for sometime and said it cannot find no file or directory in the distributions/distribution name/id_rsa. does it mean the RSA is not generated? I thought it was when I used Saml yesterday(does it matter?)...Please help. Thanks!

**Comment by sahityab** [comment]
Yes .. i figured out the base url. But about the error thing, I am able to run the build.sh until thr' it get gets me to to enter the districution name and select the authentication method and and also all those base url, etc cerdentials...but then it says as i described above ... that "no such file or directory found at distribution//distribution name/id_rsa. ". By the way I dont see it generate an rsa key before it asks for that distributiion name and authentication selection.

**Comment by sahityab** [comment]
okay..looks like it worked now...thanks so much for your quick replies..

**Comment by payton** [comment]
No problem! Glad we could get it working.

**Comment by sahityab** [comment]
👍

**Comment by payton** [comment]
First thing to check would be your configuration file located in /distribution/{distribution_name}/. Make sure the client id in that file matches the one OKTA gave you.

**Comment by sahityab** [comment]
yes it does match...

**Comment by payton** [comment]
Hmm... have you added to redirect URI to the list of accepted redirect URIs on OKTA? I've only set this up once or twice on my own, so I'm no expert on OKTA's process.

**Comment by sahityab** [comment]
yes..i did.. do u mean like adding the https://CF url/sth like index.html? 
right now i have https://CF url/index.html only. then just now, i added https://CF url to it's list.

**Comment by payton** [comment]
No. Your redirect URI should be https://{CF url}/_callback

This "/_callback" path is a temporary path for OKTA to respond to. That should be the redirect URI in your config and on OKTA.

**Comment by sahityab** [comment]
Payton...I did try with what u said..obviously it took this long for the CF to deploy ... its saying the same error again..400 Bad request and Identity Provider: Unknown
Error Code: invalid_client
Invalid value for 'client_id' parameter.

I gave 

https://d1jhdvienk4tn4.cloudfront.net/_callback in my OKTA at the Login Redirect URIs. Should i also be giving sth in the 'Initiate login uri" also?

**Comment by sahityab** [comment]
Also, i did redo the build.sh and modify the redirect uri in there...so i see it on the config file also reflected..
