### ISSUE TITLE
Continued 400 errors

### ISSUE THREAD

**Issue by sahityab** [Widen/cloudfront-auth#22]
Payton...I did try with what u said..obviously it took this long for the CF to deploy ... its saying the same error again..400 Bad request and Identity Provider: Unknown
Error Code: invalid_client
Invalid value for 'client_id' parameter.

I gave

https://d1jhdvienk4tn4.cloudfront.net/_callback in my OKTA at the Login Redirect URIs. Should i also be giving sth in the 'Initiate login uri" also?

Also, i did redo the build.sh and modify the redirect uri in there...so i see it on the config file also reflected..

**Comment by payton** [comment]
Can you double check that you are using OpenID? I don't recall specifying an 'Identity Provider' anywhere, although I could be mistaken. According to [okta](https://developer.okta.com/docs/api/resources/oidc), there is an 'idp' parameter that specifies the identity provider, but this is not used in cloudfront-auth, so it should default to okta.

**Comment by sahityab** [comment]
Now its acting weird... if i log off the oktapreview, it nicely redirects me to the oktapreview(or okta) login page...but after i give my credentials and login, it says nounce verification failed. or if i still reload it again, it says internal server error

**Comment by payton** [comment]
My apologies for the delay, I've been out of town. I created a more in-depth set of instructions for configuring OKTA that may help: https://github.com/Widen/cloudfront-auth/wiki/OKTA-Configuration#configure-lambda-and-cloudfront

Take a look at those steps and assert that everything matches on your end.

**Comment by sahityab** [comment]
Hi Payton...thanks for your reply and the detailed steps you put up on the link...But here's the differences from your steps and my configuration:

1. I don't know which version of OKTA you have been using but I do not see any "Base URI" in the process. There is just "Login Redirect URI" and that one I gave as specified by you. When I selected the create app option, i got this following screen:
![okta create app](https://user-images.githubusercontent.com/10007975/52282902-07a18500-2927-11e9-8271-9c16f2945381.PNG)
 
here i selected "web" and "Open -Id connect". 

2.In the assignments tab,I did not assign any groups to this project, but assigned people or individual, which is me alone for the time being.

3. The grant type is by default set to authorization code.

4. "Base Url--
This is named the 'Org URL' and can be found in the top right of the Dashboard tab." I did not find anything like "Org URL" in the dashboard, but from what you said the other day, i figured out that this is https://{company-name}.okta.com. Please correct me if I am wrong.

I assume when I am seeing this "Nonce Verification Failed" that there is probably a mismatch between the parameters being generated by OKTA ( Like i seen that only token is generated) and the code in teh Lambda which is checking for Nonce...
 ``` if ("cookie" in headers
                  && nonce.validateNonce(decoded.nonce, cookie.parse(headers["cookie"][0].value).NONCE))```
I removed the middle part of the && which checked for "NONCE in the value of the cookie in the header." ( Or sth like that which I don't remember exactly)


Is it possible to modify that Lambda code inside the If condition where it is validating nonce?

**Comment by sahityab** [comment]
It seems it did work after I removed the if condition for the nonce checking , but it looks like it is only working for one url.....https://d1jhdvienk4tn4.cloudfront.net/_callback...if i give https://d1jhdvienk4tn4.cloudfront.net, it is not taking me to OKTA. It is opening the website page directly...also same for any other pages/urls..like https://d1jhdvienk4tn4.cloudfront.net/index.html etc

**Comment by payton** [comment]
Please try in your browser again, but in incognito mode. The first time you go to .../index.html, for example, it will require you to login. After that, you will not need to login for however long you put under session duration. This is because your signed token is being stored as a cookie for future logins.

**Comment by sahityab** [comment]
But do u think its an okay thing to remove that nonce i condition in the Lambda?

**Comment by payton** [comment]
I would not suggest removing that bit as it adds another layer of security. It works fine with my OKTA configuration.

**Comment by sahityab** [comment]
I have tried keeping it and it is giving me the same error..."Nonce Verification Failed" (which is coming from the else part of that "if")...Can u think of any other ways to keep it ? Or as you say its another layer of security, do u think it is okay to remove that if part? Sorry I am asking you again coz its working or me only without that.

**Comment by payton** [comment]
I will leave it up to you to decide if it is necessary (https://en.wikipedia.org/wiki/Cryptographic_nonce). There are security measures in place without it and this library didn't always have the nonce verification.

**Comment by mkj28** [comment]
For me it was making sure the "Session Duration (hours)" is not 0. With 0 - the TOKEN cookie was immediately deleted and it went into redirect loop.
