### ISSUE TITLE
Improve user feedback for failed authorizations

### ISSUE THREAD

**Issue by uriahcarpenter** [Widen/cloudfront-auth#23]
If authentication or authorization fails the service provider may provide a human-readable message as a query parameter in redirected URL. These values should be preferred to be displayed to users instead of the default of `No code found`.

The params are likely SP specific, but it should be sufficient to start with a simple array of values:
```javascript
prefered_message_keys = ["error_description", "error"]
```

It would also be nice to use an HTML template to render error responses.

**Comment by payton** [comment]
401 errors addressed in 52e2964d043b130cf26a236f7d6a969a2ea060bd

**Comment by payton** [comment]
500 errors addressed in 50cf7075a5a57a113c4b8bc6d17008c094b7ba83 (static page)
