### ISSUE TITLE
NodeJS 6.10 upcoming EOL

### ISSUE THREAD

**Issue by mdc921** [Widen/cloudfront-auth#29]
**We received the following email notification from AWS about node.js 6.10 EOL in Lambda.** 

Your AWS Account currently has one or more Lambda functions using the node.js 6.10 runtime. The Node Foundation has previously published that node.js 6.x "Boron" will be declared End-of-Life (EOL) on April 2019 [1], and will stop receiving bug fixes, security updates, or performance improvements. Per the AWS Lambda runtime support policy [2], language runtimes that have reached their EOL are deprecated in AWS Lambda.

Invokes for functions configured to run on node.js 6.10 will continue to work normally, however the ability to create new Lambda functions configured to use the node.js 6.10 runtime will be disabled on April 30 2019. Code updates to existing functions using node.js 6.10 will be disabled 30 days later on May 30 2019

We encourage you to update your node.js 6.10 functions to a newer version of the Node runtime (node.js 8.10) so that you continue to benefit from important security, performance, and functionality enhancements offered by more recent releases. The newer node.js 8.10 version has improved ECMAScript support, along with other language and API improvements. The AWS Lambda programming model [3] for node.js 8.10 maintains backwards compatibility with previous versions to simplify portability. We recommend that you test your Lambda function to validate its behavior on the newer version of Node.js.

**Comment by payton** [comment]
Thanks for bringing this up. I will work on validating functionality on 8.10 and get a new version out soon.

**Comment by payton** [comment]
Not much to change here, but I updated any relevant values
dd7df141b88290b87fa4215e7ff99826a6690d26
Updating documentation where needed...
