### ISSUE TITLE
Multiple Distribution Support

### ISSUE THREAD

**Issue by uriahcarpenter** [Widen/cloudfront-auth#3]
Applying `cloudfront-auth` to multiple distributions is difficult because you must rename/remove several files each time your switch contexts.

I'm suggesting that distributions be added as a first-class citizen in the build script. The build script would first ask for a distributions name; a `distributions/my-project` directory would be created:

```
distributions
└── my-distribution
    ├── clouldfront-auth-my-distribution-lambda.zip
    ├── config.json
    ├── google-authz.json
    ├── id_rsa
    └── id_rsa.pub
```

This would give us clean separation of user data and project source code.

**Comment by payton** [comment]
Resolved in a38c98097606ceeae3069e1e71d9c23b00fa4dcf
