### ISSUE TITLE
Error while associating the Lambda ARN with cloud front 

### ISSUE THREAD

**Issue by viyomasach** [Widen/cloudfront-auth#43]
com.amazonaws.services.cloudfront.model.InvalidLambdaFunctionAssociationException: The function code size is larger than the maximum allowed size for functions that are triggered by a CloudFront event: 2548547 Max allowed: 1048576 Function: arn:aws:lambda:us-east-1:642195134287:function:cloudfrontredirect:1 (Service: AmazonCloudFront; Status Code: 400; Error Code: InvalidLambdaFunctionAssociation; Request ID: 7fa76064-c8fc-11e9-9ddd-31cabe9b12a9)

I get the above error while associating the lambdaarn with cloud front. How can I reduce the size of lambda zip file

**Comment by viyomasach** [comment]
Thank you. Finally, it worked !

**Comment by payton** [comment]
Glad to hear!
