### ISSUE TITLE
Google Groups authorization refers to undefined function

### ISSUE THREAD

**Issue by 3sGgpQ8H** [Widen/cloudfront-auth#49]
File `auth.js` used for Google Groups authorization refers to undefined function `internalServerError`.  The problem is probably in the following line: https://github.com/Widen/cloudfront-auth/blob/master/authz/google.groups-lookup.js#L47

**Comment by payton** [comment]
Thank you. The `google.groups-lookup.js` authz file is passing an extra parameter to `internalServerError` that we used to accept.

**Comment by 3sGgpQ8H** [comment]
Yes, the problem is that this extra parameter is passed as the first parameter, so callback becomes the second.  Thus function cannot call callback and breaks.
