### ISSUE TITLE
Blocking third party cookies traps user in a redirect loop

### ISSUE THREAD

**Issue by luisalguien** [Widen/cloudfront-auth#72]
After successfully authenticating against Okta the application keeps looping on a redirect due to not be able to get the cookie that the lambda@edge sets. Is there a workaround to this? Is it needed for the third party cookies be allowed in order to the lambda@edge to work?

**Comment by ashc0102** [comment]
Hi @luisalguien do u set your session duration? I resolved it by not using the default session duration which is 0. >,<

**Comment by luisalguien** [comment]
Yeah I was setting the session duration. The way we solved the issue was by using a different library for Okta on React code.
